services:
  db_1:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=accountDB
    ports:
      - 5432:5432
    volumes:
      - ./sql/create_accounts_tables.sql:/docker-entrypoint-initdb.d/create_accounts_tables.sql
  db_2:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=tasksDB
    ports:
      - 5433:5432
    volumes:
      - ./sql/create_tasks_tables.sql:/docker-entrypoint-initdb.d/create_tasks_tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
